name: API
on:
  push:
    paths:
      - 'services/api/**'
  workflow_dispatch:
jobs:
  test-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r services/api/authenticator-api/requirements.txt
      - run: pip install -r services/api/marketplace-api/requirements.txt
      - run: echo "Run tests here"
