name: CDK
on:
  push:
    paths:
      - 'services/infra/**'
      - 'services/api/**/cdk/**'
  workflow_dispatch:
jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable && pnpm i --frozen-lockfile
      - run: pnpm --filter @onetrue/cdk-infra build
      - run: echo "cdk synth would run here (requires AWS creds)"
