name: Web
on:
  push:
    paths:
      - 'apps/**'
      - 'packages/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable && pnpm i --frozen-lockfile
      - run: pnpm --filter @onetrue/app-authenticator build
      - run: pnpm --filter @onetrue/app-marketplace build
      - run: pnpm --filter @onetrue/app-website build
